# Module manifest for module 'LinuxTools'
# Generated by: dstein
# Generated on: 02/22/2024
# Last Updated: 01/08/2025
@{
	RootModule        = './linuxtools.psm1'
	ModuleVersion     = '1.0.16'
	CompatiblePSEditions = @('Core')
	GUID              = 'd2159ed4-ad33-4e57-a295-a7eb29ac60a3'
	Author            = 'skatterbrainz'
	CompanyName       = 'skatterbrainz'
	Copyright         = '(c) 2023-2025 Skatterus Maximus. All rights reserved.'
	Description       = 'An experimental PowerShell module for Linux nerds. A bit Debian/Cinnamon focused, but no reason to limit this. Because: why not?'
	PowerShellVersion = '7.4'
	# PowerShellHostName     = ''
	# PowerShellHostVersion  = ''
	# DotNetFrameworkVersion = ''
	# ClrVersion = ''
	# ProcessorArchitecture = ''
	RequiredModules   = @('psIni', 'Microsoft.PowerShell.ConsoleGuiTools')
	# RequiredAssemblies = @()
	# ScriptsToProcess = @()
	# TypesToProcess   = @()
	# FormatsToProcess = @()
	# NestedModules    = @()
	FunctionsToExport = @(
		"Get-*", "Set-*", "New-*", "Remove-*", "Invoke-*", "Update-*",
		"Test-*", "Add-*", "Start-*", "Unlock-*", "Update-*"
	)
	CmdletsToExport   = '*'
	VariablesToExport = '*'
	AliasesToExport   = '*'
	# DscResourcesToExport = @()
	# ModuleList = @()
	# FileList   = @()
	PrivateData       = @{
		PSData = @{
			Tags       = @('linux', 'disk', 'service', 'computer', 'hardware', 'account', 'system', 'process',
				'user', 'group', 'network', 'applications', 'inventory', 'skatterbrainz', 'browser', 'firefox')
			LicenseUri = 'https://github.com/Skatterbrainz/LinuxTools/blob/main/LICENSE'
			ProjectUri = 'https://github.com/Skatterbrainz/LinuxTools'
			IconUri    = 'https://github.com/user-attachments/assets/73df7f19-0c77-4353-a04d-dd67bb1274c3'
			# ReleaseNotes = ''
			# Prerelease = ''
			# RequireLicenseAcceptance = $false
			# ExternalModuleDependencies = @()
		} # End of PSData hashtable
	} # End of PrivateData hashtable
	# HelpInfoURI = ''
	# DefaultCommandPrefix = ''
}